name: Hello world

on:
  workflow_dispatch:

env:
  ENVS: |
    bk7231n
    bk7231t

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          echo ${{ vars.ENVS }}
